version: "3.8"

services:
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_config:/mosquitto/config
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 1883"]
      interval: 10s
      retries: 3
    restart: unless-stopped

  broker_monitor:
    image: ghcr.io/gent1b/iot-broker-monitor:latest   # <-- GHCR image
    pull_policy: always
    depends_on:
      - mqtt_broker
    ports:
      - "8001:8001"
    restart: unless-stopped
