services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    env_file:
      - .env
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "admin123"
      DOCKER_INFLUXDB_INIT_ORG: "${INFLUXDB_ORG}"
      DOCKER_INFLUXDB_INIT_BUCKET: "${INFLUXDB_BUCKET}"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${INFLUXDB_TOKEN}"
    restart: unless-stopped

  subscriber:
    image: ghcr.io/gent1b/iot-subscriber:latest
    pull_policy: always
    env_file:
      - .env
    environment:
      BROKER: "${BROKER}"
      INFLUXDB_URL: "${INFLUXDB_URL}"
      INFLUXDB_TOKEN: "${INFLUXDB_TOKEN}"
      INFLUXDB_ORG: "${INFLUXDB_ORG}"
      INFLUXDB_BUCKET: "${INFLUXDB_BUCKET}"
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "9273:9273"
    depends_on:
      - influxdb
      - subscriber
    restart: unless-stopped
